#define BUFFER_IOCTL_MAGIC 'p'

#define BUFFER_IOCTL_BYTESINBUFFER _IOR(BUFFER_IOCTL_MAGIC,0,int)
#define BUFFER_IOCTL_NUMREADER 	  _IOR(BUFFER_IOCTL_MAGIC,1,int)
#define BUFFER_IOCTL_BUFFERSIZE 	  _IOR(BUFFER_IOCTL_MAGIC,2,int)
#define BUFFER_IOCTL_SETSIZE 	  	  _IOWR(BUFFER_IOCTL_MAGIC,3,int)

#define BUFFER_IOCTL_MAXNR 5


